services:
  db:
    image: mysql:8.0.30
    container_name: passion_lecture_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_passion_lecture
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: passion_lecture_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
