const books = [
  {
    id: 1,
    titre: 'Le Mystère de la Chambre Jaune',
    extrait:
      'Il était une fois, dans une vieille maison de campagne, un cri perça la nuit...',
    resume:
      "Dans ce roman policier, le jeune détective François de la Roche résout une série de mystères autour d'une chambre mystérieuse.",
    annee_edition: 1907,
    nombre_de_pages: 320,
    id_categorie: 1,
    id_auteur: 1,
    id_editeur: 1,
  },
  {
    id: 2,
    titre: 'Les Misérables',
    extrait:
      "Il dort. Quoique le sort fût pour lui bien étrange, il ne vivait que pour le bien d'autrui.",
    resume:
      "L’histoire de Jean Valjean, un ancien forçat, qui cherche la rédemption tout en étant poursuivi par l'inspecteur Javert. Un roman qui explore la misère sociale et la justice.",
    annee_edition: 1862,
    nombre_de_pages: 1500,
    id_categorie: 2,
    id_auteur: 2,
    id_editeur: 2,
  },
  {
    id: 3,
    titre: '1984',
    extrait: 'War is peace. Freedom is slavery. Ignorance is strength.',
    resume:
      "Dans une société dystopique contrôlée par un régime totalitaire, Winston Smith cherche à s'échapper de l’emprise de Big Brother. Un roman de science-fiction politique puissant.",
    annee_edition: 1949,
    nombre_de_pages: 328,
    id_categorie: 3,
    id_auteur: 3,
    id_editeur: 3,
  },
  {
    id: 4,
    titre: "L'Alchimiste",
    extrait:
      "Quand vous voulez vraiment quelque chose, tout l'Univers conspire à vous aider à l'obtenir.",
    resume:
      'L’histoire de Santiago, un jeune berger andalou, en quête d’un trésor caché. Un voyage initiatique qui parle de rêves, de destin et de la quête de soi.',
    annee_edition: 1988,
    nombre_de_pages: 208,
    id_categorie: 4,
    id_auteur: 4,
    id_editeur: 4,
  },
];
const categories = [
  { id: 1, nom: 'Roman Policier' },
  { id: 2, nom: 'Roman Historique' },
  { id: 3, nom: 'Science-Fiction' },
  { id: 4, nom: 'Aventure' },
  { id: 5, nom: 'Fantasy' },
  { id: 6, nom: 'Essai / Histoire' },
  { id: 7, nom: 'Philosophie' },
  { id: 8, nom: 'Poésie' },
  { id: 9, nom: 'Biographie' },
  { id: 10, nom: 'Théâtre' },
  { id: 11, nom: 'Littérature Classique' },
  { id: 12, nom: 'Développement personnel' },
  { id: 13, nom: 'Économie' },
  { id: 14, nom: 'Santé & Bien-être' },
  { id: 15, nom: 'Jeunesse' },
  { id: 16, nom: 'Écologie' },
  { id: 17, nom: 'Religion' },
  { id: 18, nom: 'Psychologie' },
  { id: 19, nom: 'Cuisine & Gastronomie' },
  { id: 20, nom: 'Voyage' },
];

const authors = [
  { id: 1, prenom: 'Gaston', nom: 'Leroux' },
  { id: 2, prenom: 'Victor', nom: 'Hugo' },
  { id: 3, prenom: 'George', nom: 'Orwell' },
  { id: 4, prenom: 'Paulo', nom: 'Coelho' },
  { id: 5, prenom: 'J.K.', nom: 'Rowling' },
  { id: 6, prenom: 'Yuval Noah', nom: 'Harari' },
  { id: 7, prenom: 'Albert', nom: 'Camus' },
  { id: 8, prenom: 'Franz', nom: 'Kafka' },
  { id: 9, prenom: 'Marguerite', nom: 'Duras' },
  { id: 10, prenom: 'Antoine', nom: 'de Saint-Exupéry' },
  { id: 11, prenom: 'Jane', nom: 'Austen' },
  { id: 12, prenom: 'Ernest', nom: 'Hemingway' },
  { id: 13, prenom: 'Marcel', nom: 'Proust' },
  { id: 14, prenom: 'Simone', nom: 'de Beauvoir' },
  { id: 15, prenom: 'Alexandre', nom: 'Dumas' },
  { id: 16, prenom: 'Stephen', nom: 'King' },
  { id: 17, prenom: 'Agatha', nom: 'Christie' },
  { id: 18, prenom: 'Jules', nom: 'Verne' },
  { id: 19, prenom: 'Charles', nom: 'Dickens' },
  { id: 20, prenom: 'Jean-Paul', nom: 'Sartre' },
];

const editors = [
  { id: 1, nom: 'Éditions Félix' },
  { id: 2, nom: 'Éditions Classiques' },
  { id: 3, nom: 'Secker & Warburg' },
  { id: 4, nom: 'HarperCollins' },
  { id: 5, nom: 'Gallimard Jeunesse' },
  { id: 6, nom: 'Albin Michel' },
  { id: 7, nom: 'Le Livre de Poche' },
  { id: 8, nom: 'Folio' },
  { id: 9, nom: 'Actes Sud' },
  { id: 10, nom: 'Robert Laffont' },
  { id: 11, nom: 'Flammarion' },
  { id: 12, nom: 'Grasset' },
  { id: 13, nom: 'Éditions du Seuil' },
  { id: 14, nom: 'Bayard' },
  { id: 15, nom: 'Nathan' },
  { id: 16, nom: 'Hatier' },
  { id: 17, nom: 'Casterman' },
  { id: 18, nom: 'L’école des loisirs' },
  { id: 19, nom: 'Presses Universitaires de France' },
  { id: 20, nom: 'Penguin Books' },
];

export { books, categories, authors, editors };
